import React from 'react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { Container, TitlePage, TitleCreatores, Main, ButtonWrapper } from '../../styles/pages/events/style';
import MockProfile from '@/components/MockProfile';
import { Button } from '@chakra-ui/react';

export default function EasterEgg() {
    const router = useRouter();

    const handleBack = () => {
        router.push('/');
    };

    return (
        <>
            <Head>
                <title>Unicap Events | Eventos</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Main>
                <Container>
                    <TitlePage>
                        <TitleCreatores>
                            Criadores do projeto
                        </TitleCreatores>
                        <ButtonWrapper>
                            <Button bg="#6A0014" color="white" _hover={{ bg: 'red.500' }} onClick={handleBack}>
                                <span>Voltar</span>
                            </Button>
                        </ButtonWrapper>
                    </TitlePage>
                    <MockProfile />
                </Container>
            </Main>
        </>
    );
}
