import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { TitlePageHome, MainHome, ProjectDescription, DescriptionContainer, WrapperImage } from "@/styles/pages/events/style";
import { Button } from "@chakra-ui/react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();

  useEffect(() => {
    const token = localStorage.getItem('accessToken');
    if (!token) {
      router.push('/login');
    }
  }, [router]);

  const handleNavigateToEasterEgg = () => {
    router.push('/easter-egg');
  };

  return (
    <>
      <Head>
        <title>Unicap Events</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainHome className={`${styles.main} ${inter.className}`}>
      <WrapperImage>
          <img src="/ticket.jpg" alt="Descrição da imagem" />
      </WrapperImage>
        <TitlePageHome className={`${styles.h1}`}>
          Bem vindo ao unicap events!
        </TitlePageHome>
        <DescriptionContainer>
          <ProjectDescription>
            O Unicap Events é uma plataforma desenvolvida por alunos do 5º período do curso de Sistemas para Internet da Universidade Católica de Pernambuco (UNICAP). Este projeto foi realizado como parte do Trabalho de Conclusão de Curso (TCC) e tem como objetivo facilitar a organização e a participação em eventos universitários.
          </ProjectDescription>
          <ProjectDescription>
            Nossa missão é proporcionar uma ferramenta intuitiva e eficaz para gerenciar eventos, conectar alunos e promover atividades acadêmicas e sociais dentro da universidade. Esperamos que esta plataforma contribua significativamente para a comunidade acadêmica e inspire futuras gerações de desenvolvedores.
          </ProjectDescription>
          <ProjectDescription>
            Para saber mais sobre quem desenvolveu este projeto
            <Button
              bg="#6A0014"
              color="white"
              _hover={{ bg: 'red.500' }}
              onClick={handleNavigateToEasterEgg}
              marginLeft="10px" 
          >Clique aqui!</Button>
          </ProjectDescription>
        </DescriptionContainer>
      </MainHome>
    </>
  );
}
